### ISSUE TITLE
MVPレビュー用

### ISSUE THREAD

**Issue by Akira2023-29** [Akira2023-29/From-Your-Desk#148]
## 各種情報
デスク色彩診断
サービスURL: https://from-your-desk.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ]  画像解析機能
   - デスク画像アップ => Google Cloud Vision APIで解析して色彩情報取得
- [ ]  画像解析結果から診断文章生成機能
   - 画像診断結果をOpenAIに渡して診断結果取得
- [ ]  Xへシェア機能
- [ ]  診断結果の投稿機能
   - 診断一覧
   - お気に入り診断一覧
- [ ]  いいね機能
- [ ]  ログイン機能
   - ログイン・ログアウト機能
 
### MVPリリース時点で作成しなかった機能
- [ ]  パスワードリセット機能
- [ ]  管理者画面での投稿編集機能

### MVPリリース時点で追加した機能
- [ ] Googleアカウントでのソーシャルログイン機能
- [ ] マルチ検索機能
  - デスクでの作業内容+作業区分（オフィス・在宅）+作業環境での検索機能
- [ ] 楽天商品提案機能
  - 診断環境時に楽天商品提示（詳細画面）
- [ ] 診断結果集計機能（デスクの作業環境）

## サービスイメージがわかるようなスクリーンショット等
アプリトップページに説明を記載しています。
- トップページ
[![Image from Gyazo](https://i.gyazo.com/2febd005c1121e15a62aaff0129ae4df.png)](https://gyazo.com/2febd005c1121e15a62aaff0129ae4df)
- 診断ページ
[![Image from Gyazo](https://i.gyazo.com/c3d84d4b7168010c90eccbd5892c436b.png)](https://gyazo.com/c3d84d4b7168010c90eccbd5892c436b)
- 診断結果ページ
[![Image from Gyazo](https://i.gyazo.com/9cbd44cb3c6c885910252926749729ea.png)](https://gyazo.com/9cbd44cb3c6c885910252926749729ea)
- 診断一覧
[![Image from Gyazo](https://i.gyazo.com/f6471e1b5412408d12018a71c6ed1333.png)](https://gyazo.com/f6471e1b5412408d12018a71c6ed1333)

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

READMEに記載してある、
- いいね機能
- お気に入り診断一覧
ですが、**いいねしたら、お気に入り一覧に表示される**という挙動であっていますでしょうか？
(`いいね`と`お気に入り`の文言から機能の役割が違うようなイメージでしたので確認させてください。)

**Comment by Akira2023-29** [comment]
お疲れ様です。
ご確認ありがとうございます。
以下回答します。
> いいね機能
> お気に入り診断一覧
> ですが、いいねしたら、お気に入り一覧に表示されるという挙動であっていますでしょうか？
> (いいねとお気に入りの文言から機能の役割が違うようなイメージでしたので確認させてください。)

→ その挙動で合っています。いいね機能 =お気に入り機能のことです。
　文言誤り失礼しました。。。
- [ ] お気に入り機能
- [ ] 診断一覧
  - お気に入り診断一覧

**Comment by tmtkzk0823** [comment]
ご説明ありがとうございます。
MVPリリースに記載された内容が実装できていると思います！
LGTMです！

**Comment by Akira2023-29** [comment]
富田講師
レビューありがとうございます！
本リリース向けて機能追加+診断結果の出力がもっとそれらしいものになるよう修正していきます！
引き続き、よろしくお願い致します。
