### ISSUE TITLE
Webアプリレビュー（中間報告）

### ISSUE THREAD

**Issue by tmtkzk0823** [Akira2023-29/From-Your-Desk#225]
@Akira2023-29 
お疲れ様です！
アプリの中間報告ありがとうございました！
確認させていただきましたが、技術、ユーザビリティともにレベルが高く、アプリケーションとしての完成度も高いように思いました！

1点だけ、
- 写真を投稿して、診断している時間（APIからのレスポンスを待っている時間）で、ユーザーに「通信中」の情報を渡すために、**APIからのレスポンスを待っている間、ローディング画面を入れてあげる**と細かい部分までユーザビリティを意識したアプリケーションになるかと思いました！

以上です！
このまま本リリースまで走り抜けていただきたいと思います！

**Comment by Akira2023-29** [comment]
@tmtkzk0823 
富田講師
お疲れ様です。
レビューありがとうございます！

ちょうど今日の夕方ごろに診断結果を待つ間にローディング画面を表示するよう実装しました。
本番環境にも反映させましたので、お時間ある時に確認していただけると幸いです。
[![Image from Gyazo](https://i.gyazo.com/349c5a8dac2733f9a28ed168e26ba8bb.gif)](https://gyazo.com/349c5a8dac2733f9a28ed168e26ba8bb)

本リリースに向けて進めます！
引き続き、よろしくお願い致します！
