### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by Akira2023-29** [Akira2023-29/From-your-Desk#5]
### 実装予定の機能
- [ ] 画像解析機能
- [ ] 画像解析結果から診断文章生成機能
- [ ] Xへシェア機能
- [ ] 診断結果の投稿機能
- [ ] いいね機能
- [ ] ログイン機能
- [ ] パスワードリセット機能
- [ ] 管理者画面での投稿編集機能

### 必要なページ
- [ ] トップページ
- [ ] ユーザー新規登録
- [ ] ログイン
- [ ] アカウント
- [ ] アカウント編集
- [ ] パスワードリセット申請
- [ ] パスワードリセット
- [ ] 診断実行
- [ ] 診断結果表示
- [ ] 投稿一覧
- [ ] 投稿詳細
- [ ] 管理画面

**Comment by Tsuchiya2** [comment]
![スクリーンショット 2023-11-21 19 43 28](https://github.com/Akira2023-29/From-your-Desk/assets/61481161/b11ee49c-aa5a-4de7-9ef4-b414614495f9)

↑の箇所もご確認&対応をお願いいたします。

**Comment by Akira2023-29** [comment]
土屋講師、レビューありがとうございます。
失礼しました、ストリートポイントまで設定しましたが、
レビュー用のこちらに各項目の中身を記載していませんでした。
再度、ご確認のほどよろしくお願い致します。

### 概要

### 実装予定の機能
- [ ] 画像アップロード機能
- [  ] diagnosisモデル・コントローラー・ビュー作成
- [  ] gem carrrywaveインストール
- [  ] アップローダー設定（desk_imageカラムと紐付け、デフォルト画面、保存OKの拡張子等）
- [  ] ファイルアップ用のフォーム作成作成
- [  ] プレビュー表示設定
- [  ] MinMagic でサイズ調整設定 
- [ ] 画像解析機能
- [  ] Google Cloud Vision APIのAPIキー取得
- [  ] 「.env」ファイルにAPIキーを環境変数に設定（dotenv使用）
- [  ] .gitignoreファイルに「.env」追加
- [  ] リクエスト文作成
- [  ] レスポンス（JSON式のcolor情報)受け取り確認
- [  ] 受け取った情報から必要なものだけ抽出。（RGB情報など）
- [ ] 画像解析結果から診断文章生成機能
- [  ] OpenAIのAPIキー所得
- [  ]  「.env」ファイルにAPIキーを環境変数に設定（dotenv使用）
- [  ]  .gitignoreファイルに「.env」追加
- [  ] リクエスト文作成（整理した画像解析結果を渡す。AIに初期設定を与える）
- [  ] レスポンス受け取り
- [  ] DeepL API で翻訳
- [  ] ブラウザに結果を表示
- [ ] Xへシェア機能
- [  ] 診断結果（文章）ページからXにシェアボタン設置
- [  ] OGP設定
- [ ] パスワードリセット機能
- [  ] sorceryのreset_password機能をインストール
- [  ] letter_openerのメール設定
- [  ] configで環境ごとに定数を設定
- [  ] フラッシュメッセージ設定
- [ ] 管理者画面での投稿編集機能
- [  ] ルーティングでadminのnamespace設定
- [  ] userのにoleカラムを追加、enumで一般ユーザーとadminを分ける
- [  ] admin用のディレクトリにてビュー・コントローラー作成
- [  ] 掲示板の削除・編集機能
- [  ] ユーザーの削除・編集機能

### 必要なページ
- [ ] トップページ
- [  ] レイアウト作成
- [  ] ロゴ追加
- [  ] 各種ページへのリンク
- [ ] ユーザー新規登録
- [  ] userモデル・コントローラー・ビュー作成
- [  ] ルーティング設定
- [  ] usersコントローラーにてnewアクション・createアクション・ストロングパラメーター設定
- [  ] form_withを用いた登録フォーム作成
- [  ] モデルバリデーション設定
- [ ] ログイン
- [  ] gem sorcery インストール
- [  ] 新規登録画面作成
- [  ] user_sessionsコントローラー設定
- [  ] userモデル設定（バリデーション）
- [  ] マイグレーションファイルのカラム設定
- [  ] applicationコントローラーにrequire_login等の必要事項を設定
- [  ] フラッシュメッセージ設定
- [ ] アカウント
- [  ] アバター画像表示
- [  ] ユーザー名表示
- [  ] 編集ページへのリンク作成
- [ ] アカウント編集
- [  ] アバター画像編集
- [  ] ユーザー名編集
- [  ] パスワードリセット画面リンク
- [ ] パスワードリセット申請（実装予定の機能に記載）
- [ ] パスワードリセット（実装予定の機能に記載）
- [ ] 診断実行（実装予定の機能に記載）
- [ ] 診断結果表示
- [  ] 診断に使用した画像表示
- [  ] OpenAIから返された診断結果（生成された文章）を表示
- [  ] 各種リンク作成
- [ ] 投稿一覧
- [  ]  boardモデル作成・コントローラー・ビュー作成
- [  ]  診断に使用した画像を表示
- [  ]  診断結果を表示
- [ ] 投稿詳細
- [  ] 掲示板内容表示
- [  ]  削除ボタン設置（自分の投稿のみ）
- [  ] 各種リンク作成
- [ ] 管理画面（実装予定の機能に記載）

**Comment by Tsuchiya2** [comment]
意図が伝わっていないようなので、もう少し説明しますね。

GithubProject（俗にカンバン機能と呼ばれるもの）を作成して、isseuをそこに掲載して、ストーリポイントの付与まで行なって提出してください。

**Comment by Akira2023-29** [comment]
土屋講師
お疲れ様です。
こちら、GithubProjectにissueを作成済みになります。
https://github.com/users/Akira2023-29/projects/7

提出方法として、レビュー用のissueのURLを貼り付けるとのことでしたので
このissueのURLを提出しておりました。
私の勘違いでしたら申し訳ございません・・・
[![Image from Gyazo](https://i.gyazo.com/de295dd3e04c02cb5ec2f5a6dce66697.png)](https://gyazo.com/de295dd3e04c02cb5ec2f5a6dce66697)

**Comment by Tsuchiya2** [comment]
issueのURLの提出で会っています。
ただカンバンがこちらからは見えないので、private設定とかになっているかもしれません。
一度ご確認いただけますか？

![スクリーンショット 2023-11-21 20 46 15](https://github.com/Akira2023-29/From-your-Desk/assets/61481161/7be7e0ab-78da-4e0d-9e6f-68e335c96d62)

![スクリーンショット 2023-11-21 20 46 53](https://github.com/Akira2023-29/From-your-Desk/assets/61481161/d153f8a3-4695-451e-a05a-d2213b1dc9e5)

**Comment by Tsuchiya2** [comment]
確認できました。
以下コメントになります。

---

ストーリーポイント「5」を付けている issueですが、もう少し細かくしましょう。比較的トライに近いものと、これまで学習してきているものが同じ数字になっているので、トライよりのissueは調査・ページ用意・機能実装etcに細かく分けて、それぞれストーリーポイントを付けるようにした方が、進捗が分かりやすい&感じやすいかと思うので見直してみてください。

**Comment by Akira2023-29** [comment]
土屋講師
レビューありがとうございます。
以下のissue（主にトライ系）を修正しましたので、ご確認の程よろしくお願い致します。
### 調査・技術検証・実装に分けました
・Google Cloud APIの画像解析機能
・OpenAI の文章生成機能
・DeepL API の翻訳機能
・Xへのシェア機能
・パスワードリセット機能

技術検証用のアプリを作成してAPI等を試しにいろいろ触っていたので
そちらのアプリで技術検証→検証できたら実装に反映するという方向で考えています。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
検証も良いかと思います。
LGTMです。

**Comment by Akira2023-29** [comment]
土屋講師
レビューありがとうございます。
issue元に開発進めていきます。
引き続き、よろしくお願い致します。
